AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing lambda_list_table_perms function.
Resources:
  rdmsDevlisttablepermslambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      FunctionName: rdms-dev-listtableperms-lambda
      Description: 'Lambda function for listing Athena Lake Formation policies.'
      Handler: lambda_list_table_perms.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::115854119938:role/rdms-dev-lambda-etl-role
      Runtime: python3.8
      #CodeUri: ../../build/lambda_lib/lambda_list_table_perms.py
      CodeUri: ./lambda_list_table_perms.py
      Environment:
          Variables:
              CODEPIPELINE_GIT_BRANCH_NAME: dev,
              logger_level: DEBUG,
              region_name: us-west-2,
              bucket_name: rdms-dev-app-bucket,
              config_file_name: config/erm_reporting_config.json
              out_bucket_label: output,
              out_bucket_key: _temporary/etl/erm_reporting_perms.out
      Layers: ["arn:aws:lambda:us-west-2:115854119938:layer:ext-lib:1", "arn:aws:lambda:us-west-2:115854119938:layer:ucop-util:8"]
      Timeout: 300
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda_list_table_perms
      DockerTag: python3.8-v1
      ReservedConcurrentExecutions: 20
Outputs:
  rdmsDevlisttablepermslambda:
    Description: "List Table Permissions Lambda Function ARN"
    Value: !GetAtt rdmsDevlisttablepermslambda.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for List Table Permissions function"
    Value: !GetAtt rdmsDevlisttablepermslambda.Arn
